### ISSUE TITLE
NodePing_Agent is missing info on how to add checks and plugin runs to an AGENT check

### ISSUE THREAD

**Issue by TheBigBear** [NodePing/NodePing_Agent#1]
The documentation says : ```You assign or modify checks to run on your agents using either NodePing's web site or API.``` But the Nodeping website does NOT offer any UI when editing the AGENT check to add any extra plugins to be run, nor any other checks to be performed.

**Comment by NodePing** [comment]
Currently, there aren't any AGENT plugins defined so we don't have a UI for the non-existent feature.

When your AGENT check is enabled, it will appear in the 'Regions' drop down on the create/edit check modal.  By selecting the AGENT from the dropdown, you can assign that check to run on your AGENT
